class DBOperation {
    static INSERT = "INSERT_DATA_INTO_DB";
    static UPDATE = "UPDATE_DATA_INTO_DB";
    static DELETE = "DELETE_DATA_INTO_DB";
}
class MDB_LIST_CONDITION {
    static CM_COMPANY_BY_SOLUTION_DEVELOPER_FORNEWINSERT = "CM_COMPANY_BY_SOLUTION_DEVELOPER_FORNEWINSERT";
    static CM_COMPANY_BY_SOLUTION_DEVELOPER_FORUPDATERECORD = "CM_COMPANY_BY_SOLUTION_DEVELOPER_FORUPDATERECORD";

    static UM_USER_BY_COMPANYID_FORNEWINSERT = "UM_USER_BY_COMPANYID_FORNEWINSERT";
    static UM_USER_BY_COMPANYID_FORUPDATERECORD = "UM_USER_BY_COMPANYID_FORUPDATERECORD";

    static BM_BRANCH_BY_COMPANYID_FORNEWINSERT = "BM_BRANCH_BY_COMPANYID_FORNEWINSERT";
    static BM_BRANCH_BY_COMPANYID_FORUPDATERECORD = "BM_BRANCH_BY_COMPANYID_FORUPDATERECORD";
    static BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORNEWINSERT = "BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORNEWINSERT";
    static BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORUPDATERECORD = "BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORUPDATERECORD";

    static ACM_CLASS_BY_CAMPUSID_FORNEWINSERT = "ACM_CLASS_BY_CAMPUSID_FORNEWINSERT";
    static ACM_CLASS_BY_CAMPUSID_FORUPDATERECORD = "ACM_CLASS_BY_CAMPUSID_FORUPDATERECORD";

    static ASM_SUBJECT_BY_COMPANYID_FORNEWINSERT = "ASM_SUBJECT_BY_COMPANYID_FORNEWINSERT";
    static ASM_SUBJECT_BY_COMPANYID_FORUPDATERECORD = "ASM_SUBJECT_BY_COMPANYID_FORUPDATERECORD";

}
class DOCUMENT_LIST_CONDITION {
    static CM_COMPANY_BY_SEARCH_PARAMETER_UPDATECOMPANY = "CM_COMPANY_BY_SEARCH_PARAMETER_UPDATECOMPANY";
    static RSM_RIGHTSETTING_BY_SEARCH_PARAMETER_UPDATERIGHTSETTING = "RSM_RIGHTSETTING_BY_SEARCH_PARAMETER_UPDATERIGHTSETTING";
    static UM_USER_BY_SEARCH_PARAMETER_UPDATEUSER = "UM_USER_BY_SEARCH_PARAMETER_UPDATEUSER";
    static URM_USERRIGHT_BY_SEARCH_PARAMETER_UPDATEUSERRIGHT = "URM_USERRIGHT_BY_SEARCH_PARAMETER_UPDATEUSERRIGHT";
    static BM_BRANCH_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEBRANCH = "BM_BRANCH_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEBRANCH";
    static ACM_CLASS_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASS = "ACM_CLASS_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASS";
    static ASM_SUBJECT_BY_COMPANYID_SEARCH_PARAMETER_UPDATESUBJECT = "ASM_SUBJECT_BY_COMPANYID_SEARCH_PARAMETER_UPDATESUBJECT";
    static ACCM_CLASSCURRICULUM_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASSCURRICULUM = "ACCM_CLASSCURRICULUM_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASSCURRICULUM";
    static AASM_ADMISSIONSESSION_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEADMISSIONSESSION = "AASM_ADMISSIONSESSION_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEADMISSIONSESSION";
}

Object.freeze(DBOperation);
Object.freeze(MDB_LIST_CONDITION);
Object.freeze(DOCUMENT_LIST_CONDITION);
