class USER_ROLE {
    static ROLE_ADMIN = 1;
    static ROLE_DEVELOPER = 2;
    static ROLE_MANAGER = 3;
    static ROLE_DEO = 4;
    static ROLE_TEACHER = 5;
    static ROLE_STUDENT = 6;
}
class DOCUMENT_TYPE {
    static COMPANY = 1;
    static USER = 2;
    static RIGHT_SETTING = 3;
    static USER_RIGHT = 4;
    static BRANCH = 5;
    static BRANCH_SETTING = 6;
    static ACADEMIC_CLASS = 7;
    static ACADEMIC_ADMISSION_SESSION = 8;
    static ACADEMIC_SUBJECT = 9;
    static ACADEMIC_CLASS_CURRICULUM = 10;
    static ACADEMIC_CLASS_CURRICULUM_SUBJECT = 11;
}
class DOCUMENT_STATUS {
    static ACTIVE_COMPANY = 1;
    static INACTIVE_COMPANY = 2;
    static DELETED_COMPANY = 3;
    static ACTIVE_USER = 4;
    static INACTIVE_USER = 5;
    static DELETED_USER = 6;
    static ACTIVE_RIGHT_SETTING = 7;
    static INACTIVE_RIGHT_SETTING = 8;
    static ACTIVE_USER_RIGHT = 9;
    static INACTIVE_USER_RIGHT = 10;
    static ACTIVE_BRANCH = 11;
    static INACTIVE_BRANCH = 12;
    static DELETED_BRANCH = 13;
    static ACTIVE_BRANCH_SETTING = 14;
    static INACTIVE_BRANCH_SETTING = 15;
    static EXPIRED_BRANCH_SETTING = 16;
    static DELETED_BRANCH_SETTING = 17;
    static ACTIVE_ACADEMIC_CLASS = 18;
    static INACTIVE_ACADEMIC_CLASS = 19;
    static DELETED_ACADEMIC_CLASS = 20;
    static ACTIVE_ACADEMIC_ADMISSION_SESSION = 21;
    static INACTIVE_ACADEMIC_ADMISSION_SESSION = 22;
    static DELETED_ACADEMIC_ADMISSION_SESSION = 23;
    static ACTIVE_ACADEMIC_SUBJECT = 24;
    static INACTIVE_ACADEMIC_SUBJECT = 25;
    static DELETED_ACADEMIC_SUBJECT = 26;
    static ACTIVE_ACADEMIC_CLASS_CURRICULUM = 27;
    static INACTIVE_ACADEMIC_CLASS_CURRICULUM = 28;
    static DELETED_ACADEMIC_CLASS_CURRICULUM = 29;
    static ACTIVE_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 30;
    static INACTIVE_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 31;
    static DELETED_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 32;
}
class DATEPICKER_INCREMENT {
    static FOR_ADMISSION_SESSION_ROUTINE = 365;
    static FOR_ADMISSION_OPENING_ROUTINE = 20;
}

Object.freeze(USER_ROLE);
Object.freeze(DOCUMENT_TYPE);
Object.freeze(DOCUMENT_STATUS);
Object.freeze(DATEPICKER_INCREMENT);
