//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AASM_AdmissionSessionClass
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> AdmissionSessionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<bool> IsEnteryTestRequired { get; set; }
        public Nullable<bool> IsInterviewRequired { get; set; }
        public Nullable<System.DateTime> SessionStartDate { get; set; }
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
