//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AASM_AdmissionSession
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CampusId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SessionStartDate { get; set; }
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public Nullable<System.DateTime> AdmissionStartDate { get; set; }
        public Nullable<System.DateTime> AdmissionEndDate { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<bool> IsEnteryTestRequired { get; set; }
        public Nullable<bool> IsInterviewRequired { get; set; }
        public string ClassIds { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Remarks { get; set; }
    }
}
