//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Student
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CampusId { get; set; }
        public Nullable<int> AdmissionSessionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> AdmissionCategoryId { get; set; }
        public string RegistrationNumber { get; set; }
        public string StudentName { get; set; }
        public string StudentCNIC { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string DomicileDistrict { get; set; }
        public string FatherName { get; set; }
        public string FatherCNIC { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public Nullable<bool> IsFatherAlive { get; set; }
        public string GuardianName { get; set; }
        public string GuardianCNIC { get; set; }
        public string StudentMobile { get; set; }
        public string StudentEmail { get; set; }
        public string ParentMobile { get; set; }
        public string LandLine { get; set; }
        public string EmergencyMobile { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Remarks { get; set; }
    }
}
