using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace office360.Models.General
{
    public enum USER_ROLE
    {
        ROLE_ADMIN = 1,
        ROLE_DEVELOPER = 2,
        ROLE_MANAGER = 3,
        ROLE_DEO = 4,
        ROLE_TEACHER = 5,
        ROLE_STUDENT = 6,
    }
    public enum DB_OperationType
    {
        INSERT_DATA_INTO_DB = 1,
        UPDATE_DATA_INTO_DB = 2,
        DELETE_DATA_INTO_DB = 3
    }
    public enum DOCUMENT_TYPE
    {
        COMPANY = 1,
        USER = 2,
        RIGHT_SETTING = 3,
        USER_RIGHT = 4,
        BRANCH = 5,
        BRANCH_SETTING = 6,
        ACADEMIC_CLASS = 7,
        ACADEMIC_ADMISSION_SESSION = 8,
        ACADEMIC_SUBJECT = 9,
        ACADEMIC_CLASS_CURRICULUM = 10,
        ACADEMIC_CLASS_CURRICULUM_SUBJECT = 11,
        ACADEMIC_ADMISSION_SESSION_CLASS = 12,
        ACCOUNT_CHART_OF_ACCOUNT = 13,
        ACCOUNT_DISCOUNT_TYPE = 14,
        ACCOUNT_FEE_TYPE = 15,
        ACCOUNT_CLASS_FEE_STRUCTURE = 16,
        ACCOUNT_CLASS_FEE_STRUCTURE_FEE_TYPE = 17,
        STUDENT = 18,

    }
    public enum DOCUMENT_STATUS
    {
        /*
         *  1.  ACTIVE DOCUMENTS WILL BE DISPLAYED ACCURATELY
            2.  IN-ACTIVE DOCUMENTS WILL DISPLAYED IN HISTORY AND RECORDS BUT WILL NOT BE SHOWN IN REPORTS
            3.  DELETED DOCUMENTS WILL HAVE NO IMPACT.
         */
        ACTIVE_COMPANY = 1,
        INACTIVE_COMPANY = 2,
        DELETED_COMPANY = 3,

        ACTIVE_USER = 4,
        INACTIVE_USER = 5,
        DELETED_USER = 6,

        ACTIVE_RIGHT_SETTING = 7,
        INACTIVE_RIGHT_SETTING = 8,

        ACTIVE_USER_RIGHT = 9,
        INACTIVE_USER_RIGHT = 10,

        ACTIVE_BRANCH = 11,
        INACTIVE_BRANCH = 12,
        DELETED_BRANCH = 13,

        ACTIVE_BRANCH_SETTING = 14,
        INACTIVE_BRANCH_SETTING = 15,
        EXPIRED_BRANCH_SETTING = 16,
        DELETED_BRANCH_SETTING = 17,

        ACTIVE_ACADEMIC_CLASS = 18,
        INACTIVE_ACADEMIC_CLASS = 19,
        DELETED_ACADEMIC_CLASS = 20,

        ACTIVE_ACADEMIC_ADMISSION_SESSION = 21,
        INACTIVE_ACADEMIC_ADMISSION_SESSION = 22,
        DELETED_ACADEMIC_ADMISSION_SESSION = 23,

        ACTIVE_ACADEMIC_SUBJECT = 24,
        INACTIVE_ACADEMIC_SUBJECT = 25,
        DELETED_ACADEMIC_SUBJECT = 26,

        ACTIVE_ACADEMIC_CLASS_CURRICULUM = 27,
        INACTIVE_ACADEMIC_CLASS_CURRICULUM = 28,
        DELETED_ACADEMIC_CLASS_CURRICULUM = 29,

        ACTIVE_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 30,
        INACTIVE_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 31,
        DELETED_ACADEMIC_CLASS_CURRICULUM_SUBJECT = 32,

        ACTIVE_ACADEMIC_ADMISSION_SESSION_CLASS = 33,
        INACTIVE_ACADEMIC_ADMISSION_SESSION_CLASS = 34,
        DELETED_ACADEMIC_ADMISSION_SESSION_CLASS = 35,

        ACTIVE_ACCOUNT_CHART_OF_ACCOUNT = 36,
        INACTIVE_ACCOUNT_CHART_OF_ACCOUNT = 37,
        DELETED_ACCOUNT_CHART_OF_ACCOUNT = 38,

        ACTIVE_ACCOUNT_DISCOUNT_TYPE = 39,
        INACTIVE_ACCOUNT_DISCOUNT_TYPE = 40,
        DELETED_ACCOUNT_DISCOUNT_TYPE = 41,

        ACTIVE_ACCOUNT_FEE_TYPE = 42,
        INACTIVE_ACCOUNT_FEE_TYPE = 43,
        DELETED_ACCOUNT_FEE_TYPE = 44,

        ACTIVE_ACCOUNT_CLASS_FEE_STRUCTURE = 45,
        INACTIVE_ACCOUNT_CLASS_FEE_STRUCTURE = 46,
        DELETED_ACCOUNT_CLASS_FEE_STRUCTURE = 47,

        ACTIVE_ACCOUNT_CLASS_FEE_STRUCTURE_FEE_TYPE = 45,
        INACTIVE_ACCOUNT_CLASS_FEE_STRUCTURE_FEE_TYPE = 46,
        DELETED_ACCOUNT_CLASS_FEE_STRUCTURE_FEE_TYPE = 47,

        ACTIVE_STUDENT=48,
        INACTIVE_STUDENT = 49,

    }
    public enum DATEPICKER_INCREMENT
    {
        FOR_ADMISSION_SESSION_ROUTINE = 365,
        FOR_ADMISSION_OPENING_ROUTINE = 20,
    }
   
    public enum CHART_OF_ACCOUNT_TYPE
    {
        ASSETS=1,
        LIABILITIES=2,
        CAPITAL_EQUITY=3,
        REVENUE_SALE=4,
        COST_OF_SALES=5,
        EXPENSES=6
    }
    public enum FEE_CATEGORY
    {
        ACADEMIC_FEE=1,
        OTHER_FEE=2,
    }
}