using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace office360.Models.General
{
    public class DDOFilter
    {
        public enum MDBDataFilter
        {
            CM_COMPANY_BY_SOLUTION_DEVELOPER_FORNEWINSERT = 1,
            CM_COMPANY_BY_SOLUTION_DEVELOPER_FORUPDATERECORD = 2,

            UM_USER_BY_COMPANYID_FORNEWINSERT = 3,
            UM_USER_BY_COMPANYID_FORUPDATERECORD = 4,

            BM_BRANCH_BY_COMPANYID_FORNEWINSERT = 5,
            BM_BRANCH_BY_COMPANYID_FORUPDATERECORD = 6,
            BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORNEWINSERT = 7,
            BM_BRANCH_BY_ALLOWEDBRANCHIDS_FORUPDATERECORD = 8,

            ACM_CLASS_BY_CAMPUSID_FORNEWINSERT = 9,
            ACM_CLASS_BY_CAMPUSID_FORUPDATERECORD = 10,
            ACM_CLASS_BY_ADMISSIONSESSIONID_FORNEWINSERT = 11,
            ACM_CLASS_BY_ADMISSIONSESSIONID_FORUPDATERECORD = 12,

            AASM_ADMISSIONSESSION_BY_CAMPUSID_FORNEWINSERT = 13,
            AASM_ADMISSIONSESSION_BY_CAMPUSID_FORUPDATERECORD = 14,

            ASM_SUBJECT_BY_COMPANYID_FORNEWINSERT = 15,
            ASM_SUBJECT_BY_COMPANYID_FORUPDATERECORD = 16,
            ASM_SUBJECT_BY_CLASSID_FORNEWINSERT = 17,
            ASM_SUBJECT_BY_CLASSID_FORUPDATERECORD = 18,

            ACOAM_CHARTOFACCOUNT_BY_COMPANYID_ACCOUNTTYPEID_FORNEWINSERT = 19,
            ACOAM_CHARTOFACCOUNT_BY_COMPANYID_ACCOUNTTYPEID_FORUPDATERECORD = 20,

            AFTM_FEETYPE_BY_COMPANYID_FORNEWINSERT = 21,
            AFTM_FEETYPE_BY_COMPANYID_FORUPDATERECORD = 22,

            ACFSM_CLASSFEESTRUCTURE_BY_CLASSID_FORNEWINSERT = 23,
            ACFSM_CLASSFEESTRUCTURE_BY_CLASSID_FORUPDATERECORD = 24
        }
        public enum MDBDocFilter
        {
            CM_COMPANY_BY_SEARCH_PARAMETER_UPDATECOMPANY = 1,
            RSM_RIGHTSETTING_BY_SEARCH_PARAMETER_UPDATERIGHTSETTING = 2,
            UM_USER_BY_SEARCH_PARAMETER_UPDATEUSER = 3,
            URM_USERRIGHT_BY_SEARCH_PARAMETER_UPDATEUSERRIGHT = 4,
            BM_BRANCH_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEBRANCH = 5,
            ACM_CLASS_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASS = 6,
            ASM_SUBJECT_BY_COMPANYID_SEARCH_PARAMETER_UPDATESUBJECT = 7,
            ACCM_CLASSCURRICULUM_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASSCURRICULUM = 8,
            AASM_ADMISSIONSESSION_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATEADMISSIONSESSION = 9,
            ACOAM_CHARTOFACCOUNT_BY_SEARCH_PARAMETER_UPDATECHARTOFACCOUNT = 10,
            ADTM_DISCOUNTTYPE_BY_COMPANYID_SEARCH_PARAMETER_UPDATEDISCOUNTTYPE = 11,
            AFTM_FEETYPE_BY_COMPANYID_SEARCH_PARAMETER_UPDATEFEETYPE = 12,
            ACFSM_CLASSFEESTRUCTURE_BY_ALLOWEDBRANCHIDS_SEARCH_PARAMETER_UPDATECLASSFEESTRUCTURE = 13,
            SM_STUDENT_BY_CAMPUSID_SEARCH_PARAMETER_UPDATESTUDENT = 14
        }
    }

}